### ISSUE TITLE
optimize your summary view

### ISSUE THREAD

**Issue by romani** [attatrol/ahsm#1]
Now you have - http://attatrol.github.io/site_result/checkstyle_merged.html
base on discussion at : https://github.com/checkstyle/checkstyle/pull/1474

Summary for site_fix1013:
Files 	 Info 	 Warnings 	 Errors
41844 	0 	15953 	0
Got unique rows for "site_fix1013":156
Summary for site_old:
Files 	 Info 	 Warnings 	 Errors
41844 	0 	15820 	0
Got unique rows for "site_old":30

1) please make lines "Got unique rows for "site_old":30" as plain text

2) all lines with numbers are red, that mislead, please merge that summary tables in one show by RED old amount of warnigns and GREEN new amount
Expected view (instead of colors I used strikeout):

Files|Info|Warnings|Errors
-----| -----|-----| -----|
41844| 	0 |	~~15953~~ 15820 |	0

**Comment by attatrol** [comment]
@romani 
<p>
Here is <a href=http://http://attatrol.github.io/ahsm_current_example/checkstyle_merged.html>example of current report</a>.<br>
Personally i think that we should preserve all data from input sources in the merged report.<br>
What do you think about it?
</p>
<p> 
Offtopic question:<br>
1. Should i add jsoup library jar directly in my repository?<br>

**Comment by romani** [comment]
> What do you think about it?

As soon as these numbers are close to each other, your approach is good.

> Should i add jsoup library jar directly in my repository?

you can do anything in your project. Amount of dependencies are does not matter.

> Current behaviour is to delete any identical lines disregarding number of their occurencies.

if line, and message is identical in violations. It is ok to remove them.

> Should we save 9 lines from the first source in the result?

For now I can not imagine how we could generate such a report. Lets delete them all for now.

**Comment by attatrol** [comment]
@romani
I have updated <a href="http://attatrol.github.io/ahsm_current_example/checkstyle_merged.html">example of a report</a>.<br>
I will close the issue and focus on internal refactoring if you find it satisfactory.

**Comment by romani** [comment]
Looks good
